services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: rask
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rask
    ports:
      - "5433:5432"
    volumes:
      - rask_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rask"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      DB_URL: postgresql://rask:admin@db:5432/rask?sslmode=disable
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  rask_data: