// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ad.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAd = `-- name: CreateAd :one
INSERT INTO ads (title, description, price, user_id, attributes, category_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, description, price, created_at, updated_at, user_id, attributes, category_id
`

type CreateAdParams struct {
	Title       string                `json:"title"`
	Description string                `json:"description"`
	Price       int32                 `json:"price"`
	UserID      uuid.UUID             `json:"user_id"`
	Attributes  pqtype.NullRawMessage `json:"attributes"`
	CategoryID  uuid.UUID             `json:"category_id"`
}

func (q *Queries) CreateAd(ctx context.Context, arg CreateAdParams) (Ad, error) {
	row := q.db.QueryRowContext(ctx, createAd,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.UserID,
		arg.Attributes,
		arg.CategoryID,
	)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Attributes,
		&i.CategoryID,
	)
	return i, err
}

const getAdsByUser = `-- name: GetAdsByUser :many
SELECT id, title, description, price, created_at, user_id, category_id, attributes
FROM ads
WHERE user_id = $1
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type GetAdsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetAdsByUser(ctx context.Context, arg GetAdsByUserParams) ([]GetAllAdsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAdsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAdsRow
	for rows.Next() {
		var i GetAllAdsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.UserID,
			&i.CategoryID,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAds = `-- name: CountAds :one
SELECT COUNT(*) FROM ads
`

func (q *Queries) CountAds(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchAds = `-- name: SearchAds :many
SELECT id, title, description, price, created_at, user_id, category_id, attributes
FROM ads
WHERE title ILIKE '%' || $1 || '%' OR description ILIKE '%' || $1 || '%'
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type SearchAdsParams struct {
	Query  string `json:"query"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchAds(ctx context.Context, arg SearchAdsParams) ([]GetAllAdsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchAds, arg.Query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAdsRow
	for rows.Next() {
		var i GetAllAdsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.UserID,
			&i.CategoryID,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAd = `-- name: DeleteAd :exec
DELETE FROM ads
WHERE id = $1
`

func (q *Queries) DeleteAd(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAd, id)
	return err
}

const getAdsByCategory = `-- name: GetAdsByCategory :many
SELECT id, title, description, price, created_at, user_id, category_id, attributes
FROM ads
WHERE category_id = $1
   OR category_id IN (SELECT id FROM categories WHERE parent_id = $1)
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type GetAdsByCategoryParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type GetAdsByCategoryRow struct {
	ID          uuid.UUID             `json:"id"`
	Title       string                `json:"title"`
	Description string                `json:"description"`
	Price       int32                 `json:"price"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UserID      uuid.UUID             `json:"user_id"`
	CategoryID  uuid.UUID             `json:"category_id"`
	Attributes  pqtype.NullRawMessage `json:"attributes"`
}

func (q *Queries) GetAdsByCategory(ctx context.Context, arg GetAdsByCategoryParams) ([]GetAdsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getAdsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdsByCategoryRow
	for rows.Next() {
		var i GetAdsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.UserID,
			&i.CategoryID,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAds = `-- name: GetAllAds :many
SELECT id, title, description, price, created_at, user_id, category_id, attributes
FROM ads
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type GetAllAdsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllAdsRow struct {
	ID          uuid.UUID             `json:"id"`
	Title       string                `json:"title"`
	Description string                `json:"description"`
	Price       int32                 `json:"price"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UserID      uuid.UUID             `json:"user_id"`
	CategoryID  uuid.UUID             `json:"category_id"`
	Attributes  pqtype.NullRawMessage `json:"attributes"`
}

func (q *Queries) GetAllAds(ctx context.Context, arg GetAllAdsParams) ([]GetAllAdsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAds, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAdsRow
	for rows.Next() {
		var i GetAllAdsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.UserID,
			&i.CategoryID,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneAd = `-- name: GetOneAd :one
SELECT id, title, description, price, created_at, updated_at, user_id, attributes, category_id
FROM ads
WHERE id = $1
`

func (q *Queries) GetOneAd(ctx context.Context, id uuid.UUID) (Ad, error) {
	row := q.db.QueryRowContext(ctx, getOneAd, id)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Attributes,
		&i.CategoryID,
	)
	return i, err
}

const updateAd = `-- name: UpdateAd :one
UPDATE ads
SET
    title       = COALESCE($2, title),
    description = COALESCE($3, description),
    price       = COALESCE($4, price),
    attributes  = COALESCE($5, attributes),
    category_id = COALESCE($6, category_id),
    updated_at  = NOW()
WHERE id = $1
RETURNING id, title, description, price, updated_at, user_id, attributes, category_id
`

type UpdateAdParams struct {
	ID          uuid.UUID             `json:"id"`
	Title       string                `json:"title"`
	Description string                `json:"description"`
	Price       int32                 `json:"price"`
	Attributes  pqtype.NullRawMessage `json:"attributes"`
	CategoryID  uuid.UUID             `json:"category_id"`
}

type UpdateAdRow struct {
	ID          uuid.UUID             `json:"id"`
	Title       string                `json:"title"`
	Description string                `json:"description"`
	Price       int32                 `json:"price"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
	UserID      uuid.UUID             `json:"user_id"`
	Attributes  pqtype.NullRawMessage `json:"attributes"`
	CategoryID  uuid.UUID             `json:"category_id"`
}

func (q *Queries) UpdateAd(ctx context.Context, arg UpdateAdParams) (UpdateAdRow, error) {
	row := q.db.QueryRowContext(ctx, updateAd,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Attributes,
		arg.CategoryID,
	)
	var i UpdateAdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.UpdatedAt,
		&i.UserID,
		&i.Attributes,
		&i.CategoryID,
	)
	return i, err
}
