// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories(name, level, parent_id)
VALUES(
    $1,
    $2,
    $3
)
RETURNING id, name, level, parent_id, created_at
`

type CreateCategoryParams struct {
	Name     string        `json:"name"`
	Level    int16         `json:"level"`
	ParentID uuid.NullUUID `json:"parent_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.Level, arg.ParentID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategories = `-- name: GetCategories :many
SELECT 
    id,
    name,
    level,
    parent_id
FROM categories
ORDER BY level ASC
`

type GetCategoriesRow struct {
	ID       uuid.UUID     `json:"id"`
	Name     string        `json:"name"`
	Level    int16         `json:"level"`
	ParentID uuid.NullUUID `json:"parent_id"`
}

func (q *Queries) GetCategories(ctx context.Context) ([]GetCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoriesRow
	for rows.Next() {
		var i GetCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, level, parent_id
FROM categories
WHERE id = $1
`

type GetCategoryRow struct {
	ID       uuid.UUID     `json:"id"`
	Name     string        `json:"name"`
	Level    int16         `json:"level"`
	ParentID uuid.NullUUID `json:"parent_id"`
}

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (GetCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i GetCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.ParentID,
	)
	return i, err
}

const getSubcategories = `-- name: GetSubcategories :many
SELECT id, name, level, parent_id
FROM categories
WHERE parent_id = $1
ORDER BY name
`

type GetSubcategoriesRow struct {
	ID       uuid.UUID     `json:"id"`
	Name     string        `json:"name"`
	Level    int16         `json:"level"`
	ParentID uuid.NullUUID `json:"parent_id"`
}

func (q *Queries) GetSubcategories(ctx context.Context, parentID uuid.NullUUID) ([]GetSubcategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubcategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubcategoriesRow
	for rows.Next() {
		var i GetSubcategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = COALESCE($2, name),
    level = COALESCE($3, level),
    parent_id = COALESCE($4, parent_id)
WHERE id = $1
RETURNING id, name, level, parent_id
`

type UpdateCategoryParams struct {
	ID       uuid.UUID     `json:"id"`
	Name     string        `json:"name"`
	Level    int16         `json:"level"`
	ParentID uuid.NullUUID `json:"parent_id"`
}

type UpdateCategoryRow struct {
	ID       uuid.UUID     `json:"id"`
	Name     string        `json:"name"`
	Level    int16         `json:"level"`
	ParentID uuid.NullUUID `json:"parent_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Level,
		arg.ParentID,
	)
	var i UpdateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.ParentID,
	)
	return i, err
}
