// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Ad struct {
	ID          uuid.UUID
	Title       string
	Description string
	Price       int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	UserID      uuid.UUID
	Attributes  pqtype.NullRawMessage
	CategoryID  uuid.UUID
}

type Category struct {
	ID       uuid.UUID
	Name     string
	Level    int16
	ParentID uuid.NullUUID
}

type User struct {
	ID          uuid.UUID
	Name        string
	Email       string
	Password    string
	PhoneNumber sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
